#Requires -Version 5.1
<#
.SYNOPSIS
    Runs the generated AutoMap startup workflow in isolated PowerShell processes.
.DESCRIPTION
    Uses temporary configuration and synthetic DPAPI credentials. Windows mapping
    boundaries are replaced with test doubles; no real shares or credentials are changed.
#>
$ErrorActionPreference = 'Stop'
$sourcePath = Join-Path $PSScriptRoot '..\Share_Manager.ps1'
$ast = [System.Management.Automation.Language.Parser]::ParseFile($sourcePath, [ref]$null, [ref]$null)
$generated = $ast.Find({
    param($node)
    $node -is [System.Management.Automation.Language.StringConstantExpressionAst] -and
    $node.Value -like '# Auto-generated by Share Manager*'
}, $true).Value
if (-not $generated) { throw 'Generated AutoMap script not found.' }
$tempParent = [IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\')
$testRoot = Join-Path $tempParent ('ShareManagerAutoMapTests_' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $testRoot | Out-Null
$mockSource = @'
$baseFolder = $PSScriptRoot
$sharesPath = Join-Path $baseFolder 'shares.json'
$credsPath = Join-Path $baseFolder 'creds.json'
$keyPath = Join-Path $baseFolder 'key.bin'
$logPath = Join-Path $baseFolder 'LogonScript.log'
$eventsPath = Join-Path $baseFolder 'LogonScript.events.jsonl'
$scenario = [IO.File]::ReadAllText((Join-Path $baseFolder 'scenario.txt'))
$script:Attempts = 0
$journal = Join-Path $baseFolder 'operations.txt'
function Get-AutoMapExecutionContext { return @{ elevated = ($scenario -eq 'Elevated'); sessionId = 1 } }
function Get-AutoMapSmbMapping {
    param($Drive)
    if ($scenario -eq 'OtherTarget') { return @{ RemotePath = '\\other\share'; Status = 'OK' } }
    if ($scenario -in @('AlreadyConnected', 'Stale', 'OpenFiles')) { return @{ RemotePath = '\\test-server\docs'; Status = 'Unavailable' } }
    return $null
}
function Get-AutoMapLocalDrive { param($Drive) return $null }
function Invoke-AutoMapNetUseQuery { param($Drive, $TimeoutSeconds) return '' }
function Set-AutoMapCredentialTarget {
    param($ServerTarget, $Username, $Password)
    Add-Content -LiteralPath $journal -Value 'Save'
    return @{ Updated = $true; ExitCode = 0 }
}
function Test-AutoMapDriveAccess {
    param($Drive, $TimeoutSeconds)
    return ($scenario -eq 'AlreadyConnected' -or ($script:Attempts -gt 0 -and $scenario -notin @('Inaccessible', 'OpenFiles')))
}
function Invoke-AutoMapNetUseDelete {
    param($Drive, $TimeoutSeconds)
    Add-Content -LiteralPath $journal -Value 'Delete'
    if ($scenario -eq 'OpenFiles') { return @{ ExitCode = 2401 } }
    return @{ ExitCode = 0 }
}
function Invoke-AutoMapNetUseMap {
    param($Drive, $Share, $Username, $Password, $TimeoutSeconds, $CredentialPrepared)
    if (-not $CredentialPrepared) { throw 'Successful bare-server credential preparation was not recognized.' }
    if ($Username -ne 'synthetic-user' -or $Password -ne 'synthetic-password') { throw 'Unexpected credential passed to mapping.' }
    Add-Content -LiteralPath $journal -Value 'Map'
    $script:Attempts++
    $code = 0
    if ($scenario -eq 'Authentication') { $code = 1326 }
    if ($scenario -eq 'SessionConflict') { $code = 1219 }
    if ($scenario -eq 'DelayedNetwork' -and $script:Attempts -lt 3) { $code = 53 }
    if ($scenario -in @('Stale', 'OpenFiles') -and $script:Attempts -eq 1) { $code = 85 }
    return @{ ExitCode = $code; Output = "System error $code"; Backend = 'Test'; CredentialsSaved = $true }
}
function Start-Sleep { param($Seconds) Add-Content -LiteralPath $journal -Value "Wait:$Seconds" }
'@

try {
    $cases = @(
        @{ Name = 'Fresh'; Exit = 0; Maps = 1; Deletes = 0; Waits = 0 },
        @{ Name = 'MissingCredentials'; Exit = 1; Maps = 0; Deletes = 0; Waits = 0 },
        @{ Name = 'CorruptCredentials'; Exit = 1; Maps = 0; Deletes = 0; Waits = 0 },
        @{ Name = 'MissingConfig'; Exit = 1; Maps = 0; Deletes = 0; Waits = 0 },
        @{ Name = 'OtherTarget'; Exit = 1; Maps = 0; Deletes = 0; Waits = 0 },
        @{ Name = 'AlreadyConnected'; Exit = 0; Maps = 0; Deletes = 0; Waits = 0 },
        @{ Name = 'DelayedNetwork'; Exit = 0; Maps = 3; Deletes = 0; Waits = 2 },
        @{ Name = 'Authentication'; Exit = 1; Maps = 1; Deletes = 0; Waits = 0 },
        @{ Name = 'SessionConflict'; Exit = 1; Maps = 1; Deletes = 0; Waits = 0 },
        @{ Name = 'DuplicateDrive'; Exit = 1; Maps = 0; Deletes = 0; Waits = 0 },
        @{ Name = 'Inaccessible'; Exit = 1; Maps = 3; Deletes = 0; Waits = 2 },
        @{ Name = 'Stale'; Exit = 0; Maps = 2; Deletes = 1; Waits = 1 },
        @{ Name = 'OpenFiles'; Exit = 1; Maps = 1; Deletes = 1; Waits = 0 },
        @{ Name = 'Elevated'; Exit = 2; Maps = 0; Deletes = 0; Waits = 0 }
    )
    foreach ($case in $cases) {
        $caseRoot = Join-Path $testRoot $case.Name
        New-Item -ItemType Directory -Path $caseRoot | Out-Null
        Set-Content -LiteralPath (Join-Path $caseRoot 'scenario.txt') -Value $case.Name -NoNewline
        $config = @{ Shares = @(@{ DriveLetter = 'Z'; SharePath = '\\test-server\docs'; Username = 'synthetic-user'; Name = 'Test'; Enabled = $true }); Preferences = @{ NetUseTimeoutSeconds = 5 } }
        if ($case.Name -eq 'DuplicateDrive') { $config.Shares += $config.Shares[0].Clone() }
        if ($case.Name -ne 'MissingConfig') { $config | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $caseRoot 'shares.json') }
        if ($case.Name -ne 'MissingCredentials') {
            $encrypted = ConvertTo-SecureString 'synthetic-password' -AsPlainText -Force | ConvertFrom-SecureString
            if ($case.Name -eq 'CorruptCredentials') { $encrypted = 'not-a-valid-encrypted-credential' }
            @{ Entries = @(@{ Username = 'synthetic-user'; EncryptionType = 'DPAPI'; Encrypted = $encrypted }) } | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $caseRoot 'creds.json')
        }
        $testScript = $generated.Replace('# Rotate and write a start marker', $mockSource + "`r`n# Rotate and write a start marker")
        $testScript = $testScript.Replace('Local\ShareManager.AutoMap', ('Local\ShareManager.AutoMap.Test.' + [guid]::NewGuid().ToString('N')))
        $scriptPath = Join-Path $caseRoot 'AutoMap.ps1'
        Set-Content -LiteralPath $scriptPath -Value $testScript -Encoding UTF8
        $output = & "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $scriptPath 2>&1
        if ($LASTEXITCODE -ne $case.Exit) { throw "$($case.Name): expected exit $($case.Exit), got $LASTEXITCODE. $output" }
        if ($case.Name -eq 'Fresh') {
            $log = Get-Content -LiteralPath (Join-Path $caseRoot 'LogonScript.log') -Raw
            if ($log -notmatch 'Found 1 total shares \(1 enabled, 0 disabled\)') { throw 'Incorrect single-share counts.' }
            if ($log -match '\[DEBUG\]|Server credential preparation failed') { throw 'Unexpected diagnostic noise in normal log.' }
            $events = Get-Content -LiteralPath (Join-Path $caseRoot 'LogonScript.events.jsonl') -Raw
            if ($events -notmatch 'Prepared Windows credential target') { throw 'Diagnostic events were lost.' }
        }
        $journalPath = Join-Path $caseRoot 'operations.txt'
        $operations = if (Test-Path -LiteralPath $journalPath) { @(Get-Content -LiteralPath $journalPath) } else { @() }
        if (@($operations | Where-Object { $_ -eq 'Map' }).Count -ne $case.Maps -or
            @($operations | Where-Object { $_ -eq 'Delete' }).Count -ne $case.Deletes -or
            @($operations | Where-Object { $_ -eq 'Wait:30' }).Count -ne $case.Waits) {
            throw "$($case.Name): unexpected operations: $($operations -join ', ')"
        }
        Write-Host "[OK] $($case.Name)"
    }
    Write-Host "[OK] $($cases.Count) generated AutoMap process scenarios passed."

    $launcher = $ast.Find({
        param($node)
        $node -is [System.Management.Automation.Language.ExpandableStringExpressionAst] -and $node.Value -like '@echo off*'
    }, $true).Value
    if (-not $launcher) { throw 'Generated CMD launcher not found.' }
    foreach ($expected in @(0, 7)) {
        $launcherRoot = Join-Path $testRoot ("Launcher & bang! $expected")
        $appFolder = Join-Path $launcherRoot 'Share_Manager'
        New-Item -ItemType Directory -Path $appFolder -Force | Out-Null
        Set-Content -LiteralPath (Join-Path $appFolder 'Share_Manager_AutoMap.ps1') -Value "exit $expected"
        $launcherPath = Join-Path $launcherRoot 'Startup.cmd'
        $launcherContent = $launcher.Replace('%APPDATA%', $launcherRoot).Replace('%TEMP%', $launcherRoot)
        Set-Content -LiteralPath $launcherPath -Value $launcherContent -Encoding ASCII
        $startInfo = New-Object System.Diagnostics.ProcessStartInfo
        $startInfo.FileName = $env:ComSpec
        $startInfo.Arguments = '/d /v:off /s /c ""{0}" HIDDEN"' -f $launcherPath
        $startInfo.UseShellExecute = $false
        $startInfo.CreateNoWindow = $true
        $startInfo.RedirectStandardOutput = $true
        $process = [System.Diagnostics.Process]::Start($startInfo)
        try {
            if (-not $process.WaitForExit(30000)) {
                $process.Kill()
                throw 'CMD launcher exceeded its test timeout.'
            }
            if ($process.ExitCode -ne $expected) { throw "CMD launcher expected exit $expected, got $($process.ExitCode)." }
            $consoleOutput = $process.StandardOutput.ReadToEnd()
            if ($consoleOutput -notmatch 'is reconnecting your network drives' -or
                $consoleOutput -notmatch 'may retry' -or
                -not $consoleOutput.Contains($appFolder + '\LogonScript.log')) { throw 'Missing AutoMap startup guidance.' }
            if ($expected -eq 0 -and $consoleOutput -notmatch 'AutoMap finished') { throw 'Missing console completion message.' }
            if ($expected -ne 0 -and $consoleOutput -notmatch 'AutoMap needs attention') { throw 'Missing console failure message.' }
        } finally { $process.Dispose() }
        $launcherLog = Get-Content -LiteralPath (Join-Path $appFolder 'LogonScript.log') -Raw
        if ($expected -eq 0 -and $launcherLog -notmatch 'completed successfully') { throw 'Missing launcher success message.' }
        if ($expected -ne 0 -and $launcherLog -notmatch 'failed with exit code 7') { throw 'Missing launcher failure message.' }
        Write-Host "[OK] CMD launcher exit $expected with spaces and shell characters in its path."
    }
} finally {
    $resolved = [IO.Path]::GetFullPath($testRoot)
    if ((Split-Path -Parent $resolved) -ne $tempParent -or (Split-Path -Leaf $resolved) -notlike 'ShareManagerAutoMapTests_*') {
        throw 'Refusing cleanup outside the test temporary directory.'
    }
    Remove-Item -LiteralPath $resolved -Recurse -Force
}
